# Generated by Django 3.2.19 on 2023-06-24 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoppinglist', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoppinglist',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='shoppinglist',
            name='quantity',
            field=models.CharField(max_length=200),
        ),
    ]
